# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balanca', '0003_auto_20170929_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesagem',
            name='highlighted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pesagem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
