# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanca', '0004_auto_20171207_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesagem',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='pesagem',
            name='owner',
        ),
    ]
