# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 23:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('balanca', '0005_auto_20171207_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='pesagem',
            name='data',
        ),
        migrations.RemoveField(
            model_name='pesagem',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pesagem',
            name='dataEHoraDePesagem',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataEHoraDePesagem'),
        ),
        migrations.AddField(
            model_name='pesagem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesagem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pesagem',
            name='peso',
            field=models.FloatField(max_length=6, verbose_name='peso'),
        ),
    ]
